updated sklean code for api prediction
GoogleCloudPlatform/asl-ml-immersion pull request #176
Opened 2022-03-16 05:37 UTC by takumiohym

ISSUE #171 
Updated sklean code for api prediction.
Confirmed it works on Vertex AI prediction.

<img width="800" alt="Screen Shot 2022-03-16 at 13 43 28" src="https://user-images.githubusercontent.com/6895245/158518986-1752998f-61d1-4087-b2eb-61fddca847e4.png">

2022-03-24 22:38 UTC, sanjanalreddy requested changes
Is there a way to keep the feature names in the inputs but change the way we pass the instances to the prediction service? Using slices is not very readable and also not a good practice since it heavily relies on the order of the columns.

2022-03-24 22:38 UTC, sanjanalreddy commented on notebooks/kubeflow_pipelines/cicd/labs/trainer_image/train.py
> +    numeric_feature_indexes = slice(0, 10)
I actually prefer the readability of listing out the features rather than using slices.

2022-03-24 22:38 UTC, sanjanalreddy commented on notebooks/kubeflow_pipelines/cicd/labs/trainer_image/train.py
> +    categorical_feature_indexes = slice(10, 12)
Especially when going through the lab with the students, it makes sense to explicitly have the columns listed out clearly.

2022-03-24 23:00 UTC, sanjanalreddy approved these changes

2022-03-24 23:28 UTC, BenoitDherin reviewed
I agree with @sanjanalreddy that it would be better to avoid slices if it is possible. 
Nit: "indexes" -> "indices

Otherwise: LGTM

Thanks for fixing that!

2022-03-24 23:47 UTC, takumiohym commented
Thanks for the comment.
So far I followed walkthrough lab that uses indices for deployment purpose, but ideally I agree with you.

https://github.com/GoogleCloudPlatform/asl-ml-immersion/blob/35e352bb5c32ac3d778f4b65d0dd79a55757d140/notebooks/kubeflow_pipelines/walkthrough/solutions/kfp_walkthrough_vertex.ipynb?short_path=13cc590#L274-L275

Maybe in the near future we should use custom prediction routine to deal with this.

So can I merge this so far?

2022-03-25 16:26 UTC, BenoitDherin commented
@takumiohym You can merge from my end. Thanks!

2022-03-25 21:35 UTC, sanjanalreddy commented
@takumiohym works for me too!

2022-03-26 01:44 UTC, merged